#!/usr/bin/env bash

# Time out

if [ -z "$LEDGER_TIMELOG" ]; then
  echo '$LEDGER_TIMELOG not set. Set it to the path of the timelog file.' >&2
  exit 1
fi

if [ ! -e "$LEDGER_FILE" ]; then
  echo "Timer not running."
  exit 1
fi

last=$(tail -1 "$LEDGER_TIMELOG")
if [ ${last:0:1} = 'o' ]; then
  echo "Timer not running."
else
  time="$(date -j +'%Y-%m-%d %H:%M:%S %z')"
  echo "o $time" >> "$LEDGER_TIMELOG"
  rev_tail=$(echo $last | cut -d ' ' -f 5- | rev)
  payee=$(echo $rev_tail | cut -d ' ' -f 1 | rev)
  account=$(echo $rev_tail | cut -d ' ' -f 2- | rev)
  echo -e "\033[1;31m[STOP]\033[0m $payee \033[1;34m($account)\033[0m $time"
fi
